FROM python:latest

RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y vim
RUN apt-get install -y nano
RUN apt-get install -y git
RUN apt-get install -y build-essential

WORKDIR /app

COPY . .

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

RUN uv sync

RUN chmod 777 /app/app/scripts/entry
RUN chmod 777 /app

ENV PATH="/app/.venv/bin:$PATH"

VOLUME ["/app/logs"]

ENTRYPOINT ["bash", "/app/app/scripts/entry"]
