
FROM python:3.12-slim


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

COPY app ./app

RUN useradd -m appuser
USER appuser

EXPOSE 8000


VOLUME ["/app/app/db"]

CMD ["uv", "run", "litestar", "run", "--host", "0.0.0.0", "--port", "8000"]


